### ISSUE TITLE
happner-client loses subscriptions on renewed login

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#278]
a new happn client is created on login (JW change)
previously the old happn client persisted and continued to receive publications
this needs to be resolved in conjunction with https://github.com/happner/happner-client/issues/6

**Comment by southbite** [comment]
How do we test for this (short paragraph about the test process) - is there an existing test in old happn?

**Comment by JohanvdWest** [comment]
The problem is not happn related, but happner. The fact that happner creates a new happn client with every login means the subscriptions done through the previous login is lost.

A test procedure would be:
- Login with happner client
- Subscribe to some event
- Trigger the event and make sure we get it.
- Login with same happner client
- Trigger the event again and make sure we get it.

The only clean solution I can think of here is to reuse the existing happn client instead of creating a new one. Other than that we would need happner to keep a record of all the subscriptions done and redo them on reconnect.

**Comment by JensEggers** [comment]
@southbite can we close this issue, seeing that it's in Released & Published?

**Comment by JensEggers** [comment]
@southbite pls point me at the PR/commit that fixes this

**Comment by southbite** [comment]
I assume this is for instances when we need to refresh the token?

**Comment by southbite** [comment]
this is to do with the device registration, the cloud user registers the device with their credentials, the device then registers with its own credentials. The device then needs to change the user it is logged in on.

This has been done externally in nsoft's endpoint component: https://github.com/FieldServer/happner-endpoint/blob/master/lib/happner-endpoint.js#L86

**Comment by JensEggers** [comment]
can close, being replaced by happner-2 endpoint option to preserve subscriptions on renewed login
