### ISSUE TITLE
Add middleware before the static middleware on www

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happner#49]
We could add more middleware on the static webroute for the www component.

Creating branch bug/#49 for this issue with unit test 10.

**Comment by nomilous** [comment]
Fixed. __But only for 'www' component.__

The real problem is that we've stretched an inflexible config design too far.

Originally it was this:
```javascript
routes: {
  'dirOnDiskAndWeb': 'middlewareFunctionName' // or array of
}
```

Then we made it do this:
```javascript
routes: {
  'static': '/a/directory/to/server/from'  // serves from /componentname  (without /static)
}
```

So now sometimes the thing on the left is a directory and sometimes it's the thing on the right that's the directory.

And i suspect the case of static directory with array on right...
```javascript
routes: {
  'static': ['middleware1', 'directory/name']
}
```
...places `middleware1` at __/component/static__  and `directory/name` at __/component__

so What we really need is to [Make a more flexible web route config design](https://github.com/happner/happner/issues/52)

**Comment by JohanvdWest** [comment]
I did not know you could do all these things now... :)

Agreed.
